### ISSUE TITLE
Add warnings and issues throughout the code to send.

### ISSUE THREAD

**Issue by wh1ter0se** [wh1ter0se/PowerUp-2018#102]
I think sending status updates for subsystem instantiation, command calls, and CyborgCommand progress to the driver station could be really useful for driver awareness. Could potentially make program debugging even easier too.

**Comment by meads594** [comment]
I'm not sure what is available in the driver station interface, but most logging tools have a lot of flexibility. For example, you can typically log an "error", a "warning", or an "info" message. Sometimes, it will also allow for an integer "level" associated with each message. This makes displaying (or searching through) log message very configurable and easy.

**Comment by wh1ter0se** [comment]
Good enough.
