### ISSUE TITLE
Detect if the bot is tipping

### ISSUE THREAD

**Issue by brogan20** [wh1ter0se/PowerUp-2018#106]
Using the built in gyroscope, we want to detect if the bot is approaching its tipping point and force it to return to a safe state to prevent the bot from breaking.

**Comment by SoWaky** [comment]
Here is a link to info on using the Accelerometer built into the roborio:
https://wpilib.screenstepslive.com/s/currentCS/m/java/l/599712-accelerometers-measuring-acceleration-and-tilt

**Comment by wh1ter0se** [comment]
Done, but needs testing.
