### ISSUE TITLE
Tune rudimentary PIDF config so we can test autonomous (and figure out what F is???)

### ISSUE THREAD

**Issue by wh1ter0se** [wh1ter0se/PowerUp-2018#123]

**Comment by brogan20** [comment]
Chapter 12 of the Talon SRX Software Reference Manual is a walk-through of tuning everything

**Comment by wh1ter0se** [comment]
@brogan20 We need to figure out why the getAndSets for PIDF aren't sending though. We can't tune if we can't configure.

**Comment by brogan20** [comment]
There always is the web interface. The software manual says that works just as well.

**Comment by wh1ter0se** [comment]
@brogan20 Wouldn't we have to set it for every talon, every time if we did that? Plus we would be tethered in testing

**Comment by brogan20** [comment]
I mean we'd have to either way. Since the bot is pulling to the right we're going to need different values for each side

**Comment by brogan20** [comment]
For the F value, it seems we'll have to be tethered to calculate it too
