### ISSUE TITLE
Spring cleaning. We really need it.

### ISSUE THREAD

**Issue by wh1ter0se** [wh1ter0se/PowerUp-2018#125]
Clean out unused variables. Streamline code for readability. Generally just make the code easier to work with.

**Comment by brogan20** [comment]
Scarily enough, I'm not sure there are many unused variables. If I recall, I think there's only like 3 constants that aren't used

**Comment by wh1ter0se** [comment]
@brogan20 I'm talking about everywhere. Structures that don't make sense, imports that were used before but now just clutter, etc.

**Comment by brogan20** [comment]
IntelliJ to the rescue! (import cleaning at least)

**Comment by brogan20** [comment]
Imports are done being optimized. Every one unused is gone

**Comment by wh1ter0se** [comment]
@brogan
