### ISSUE TITLE
The master plan for Saturday

### ISSUE THREAD

**Issue by wh1ter0se** [wh1ter0se/PowerUp-2018#179]
Alright, we want auto working by the end of tomorrow. We have been waiting for our trial by fire for the past 6 matches and it has not been on our side a single time. 

We are NOT touching the code for first match tomorrow. If we still don't have our trial by fire after that first match, we are going to add code to the foreign switch that will simply rotate (NOT DROP) after we cross the line to make sure our loop works.

Now we have an hour between our second and third qualifier, so in that time we want to accomplish the following from highest to lowest priority:
- [ ] Test and verify that the timeout on DriveUntilError works
- [ ] Test and verify that center auto works
- [ ] Test and verify that scale code logic is correct

And now we pray

**Comment by brogan20** [comment]
Since we're overhauling everything autonomous, this doesn't really apply anymore.
