### ISSUE TITLE
Add a function to broadcast field setup.

### ISSUE THREAD

**Issue by wh1ter0se** [wh1ter0se/PowerUp-2018#48]
[How to access field setup.](http://wpilib.screenstepslive.com/s/currentCS/m/getting_started/l/826278-2018-game-data-details)

DriverStation.getInstance().getGameSpecificMessage() will return a string [L/R][L/R][L/R], in the order of [our scale][switch][opponent's scale].

I'm debating between declaring it in constants or in one of the autonomous classes.

**Comment by brogan20** [comment]
I'd put it in an autonomous class myself

**Comment by wh1ter0se** [comment]
Just realized I didn't commit last night. I added a direction enum [left,right], and a field class in the util folder, with 3 get methods for each obstacle. 

Revision: I didn't commit yet because I need to move WPILib18 over first, it relies on a new method.

**Comment by wh1ter0se** [comment]
@brogan20 I'll try to take care of it after the meeting tonight.

**Comment by wh1ter0se** [comment]
Just added it and updated wpilib
