### ISSUE TITLE
Look into FMS variables.

### ISSUE THREAD

**Issue by wh1ter0se** [wh1ter0se/PowerUp-2018#53]
FMS provides variables through NetworkTables every year, so we need to figure out if they will provide with the current state of each scale and the switch (which direction its tilted). If we plan to make cube dropping sub-autonomous, this would be incredibly useful.

**Comment by SoWaky** [comment]
This is the link to info on the FMS data. Look at THE DATA section.
The plate colors are not published by FMS until after the starting countdown is complete.  So our program has to be constantly looping and checking for that data to be published. As soon as we see the colors published the program has to calculate the path and start driving.

http://wpilib.screenstepslive.com/s/currentCS/m/getting_started/l/826278-2018-game-data-details
