### ISSUE TITLE
Get the neopixels wired and ready to test.

### ISSUE THREAD

**Issue by wh1ter0se** [wh1ter0se/PowerUp-2018#60]
Pretty sure Mrs. Fox said that the part @brogan20 needed to wrap up his wiring will be here Tuesday or Wednesday. The sooner we can get that wired the better, because we need to demonstrate that neopixels are viable before we buy a bunch for the bot, and if we wait too long they may go out of stock on all of the useful lights.

**Comment by meads594** [comment]
I put a comment under #38 - I did get the NeoPixels working last night. We should think about how the wiring should done on the robot, but may want to wait until we now where things will be mounted, and how the NeoPixels will be used, before finalizing anything.
