### ISSUE TITLE
Create the GRIP pipeline for CyborgCommandAscend.

### ISSUE THREAD

**Issue by wh1ter0se** [wh1ter0se/PowerUp-2018#81]
This can be calibrated later, but we want to have it ready as soon as possible. It needs to locate the two pieces of reflective tape using a webcam mounted on the candy cane, and then quickly approach (adjusting left and right as needed), drop the hook on the bar, and then ascend.

**Comment by meads594** [comment]
Remember that the reflective tape is on the switch and not the scale. So, it won't help for locating the bar. There is a pattern on the side of the scale. I don't know how hard (or easy) it would be to pick up on it. 
![image](https://user-images.githubusercontent.com/16612316/35545278-ef0a2d52-0533-11e8-8ffd-1576a5cbdb08.png)

**Comment by brogan20** [comment]
Mr. Eads is right: The rungs have no reflective tape on them so we can't detect them through vision, or at least not as easily as with reflective tape. If we really want to detect the rungs we'll likely need another method or to do nearly all detection at competition.
