### ISSUE TITLE
Figure out a way to run NeoPixels without Arduino.

### ISSUE THREAD

**Issue by wh1ter0se** [wh1ter0se/PowerUp-2018#91]
We're 6 pounds over budget, so we may have to take out the Duino if we can. We would need to wire the pixels and the sensors straight to the RoboRio pins.

**Comment by meads594** [comment]
It shouldn't be a problem to attach the NeoPixels to a digital or (SPI) pin on the RoboRIO. We can pull the 5V power either directly from the RoboRIO or from the power breakout module. The hard part is getting the RoboRIO to send the proper commands (or even figuring out what those are). 

I would suggest poking around to see if another team has existing java code out there.

**Comment by wh1ter0se** [comment]
@brogan20 Declares it is impossible
