### ISSUE TITLE
Migrate old PID-Autonomous commands.

### ISSUE THREAD

**Issue by wh1ter0se** [wh1ter0se/PowerUp-2018#98]
We need to add all of our old movement commands so that we can create CommandGroupAuto:
- [x] CommandDriveDistance
- [x] CommandDriveDirect
- [x] CommandWait
- [x] CommandDriveUntilError
- [x] CommandRotate (reconfigured for the new tape setup)

**Comment by brogan20** [comment]
All commands completed
