### ISSUE TITLE
Figure out why the flywheels aren't receiving run values.

### ISSUE THREAD

**Issue by wh1ter0se** [wh1ter0se/PowerUp-2018#99]

**Comment by wh1ter0se** [comment]
AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

No bugs found so far. Talons won't display on the web config so we're going to try to fix that first.

**Comment by brogan20** [comment]
More info/instructions: https://github.com/CrossTheRoadElec/Phoenix-Documentation/blob/master/README.md#installing-phoenix-framework-onto-your-frc-robot

Phoenix framework download: http://www.ctr-electronics.com/control-system/hro.html#product_tabs_technical_resources

Good luck!

**Comment by wh1ter0se** [comment]
"A workaround bypassing any command structure has been implemented and works. Subject to change if the command issue is figured out"
-Probably Brogan

**Comment by wh1ter0se** [comment]
@brogan20 why are you violently opposed to just commenting with your own account

**Comment by wh1ter0se** [comment]
Also we can put this on the backburner for now, but we should figure this out and make a clean solution for it in the next couple weeks. Trust me, we do _**not**_ want to walk into competition with inexplicable patches being heavily relied on in our code. We get enough inexplicable errors as is.

**Comment by wh1ter0se** [comment]
Closing this for now because we have higher priorities than fixing that patch.
